
name: Deploy via OIDC & SSM

on:
  push:
    branches: [ master, develop ]

permissions:
  id-token: write   # Required for requesting the JWT
  contents: read    # Required for actions/checkout

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/master' && 'development' || 'test' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v5.1.0
        with:
          dotnet-version: 8.0.x

      
      - name: Build and Publish .NET
        run: |
          dotnet publish -c Release -o ./publish
        

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Archive the artifact
        run: |
          cd publish
          zip -r ../app-${{ github.sha }}.zip .

      - name: Upload artifact to S3
        run: |
          aws s3api put-object \
            --bucket adarsh4ce-bucket \
            --key ${{ github.ref_name }}/app-${{ github.sha }}.zip \
            --body app-${{ github.sha }}.zip

      # - name: Deploy via SSM
      #   run: |
      #     aws ssm send-command \
      #       --instance-ids "${{ secrets.EC2_INSTANCE_ID }}" \
      #       --document-name "AWS-RunShellScript" \
      #       --parameters 'commands=["cd /var/www/webapp", "git pull origin main", "dotnet publish -c Release", "sudo systemctl restart webapp"]' \
      #       --region us-east-1
